In [73]:
import numpy as np
from math import e

In [74]:
X = np.array([160, 170, 180, 190])

X

array([160, 170, 180, 190])

In [75]:
y = np.array([0, 0, 1, 1])

y

array([0, 0, 1, 1])

In [76]:
X_mean = np.mean(X) # 평균값
X_mean

np.float64(175.0)

In [77]:
X_std = np.std(X) # 표준편차
X_std

np.float64(11.180339887498949)

In [ ]:
X_norm = (X-X_mean) / X_std  # 정규화 공식 (X 에서 평균 빼준 값을 표준편차로 나눈 값)
X_normㅋ

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [79]:
a = 0.1
b = 0.0

In [80]:
def sigmoid(H):
    return 1 / (1+ e**(-H))

In [81]:
H_X = X * a + b

H_X

array([16., 17., 18., 19.])

In [82]:
Z_X = sigmoid(H_X)
Z_X

array([0.99999989, 0.99999996, 0.99999998, 0.99999999])

In [83]:
a_미분값 = np.mean((Z_X - y ) * X) 

a_미분값

np.float64(82.49999278763815)

In [84]:
epochs = 1000
epsilon = 1e-7 # 주의 : 붙여서 써야 인식함.

In [85]:
epsilon

1e-07

In [86]:
1 - epsilon

0.9999999

In [87]:
learning_rate = 0.1 # 학습 가중치
epochs = 1000


In [88]:
for epoch in range(10):
    H = a * X_norm + b
    print(f"H = {H}") # 선형 회귀 값

    z = sigmoid(H)
    print(f"z = {z}") # 시그모이드 값
    
    grad_a  = np.mean((z - y) * X_norm)
    print(f"grad_a = {grad_a}")
    
    grad_b = np.mean((z-y))
    print(f"grad_b = {grad_b}")
    
    a = a - learning_rate * grad_a
    b = b - learning_rate * grad_b
    
    print(f"update a = {a}, update b = {b}")
    # z 가 epsilon 보다 작으면 epsilon 리턴 → - 무한대 epsilon 리턴 → 10 - 7
    # z 가 epsilon 보다 작으면 1 - epsilon 리턴 → 무한대 1 - epsilon 리턴 → 0.9999 리턴
    z_safe = np.clip(z, epsilon, 1- epsilon) # 0 값을 방지 하기 위함
    costs = -(y * np.log(z_safe) + (1-y)* np.log(1-z_safe))
    # costs = -(y * np.log(z) + (1-y)* np.log(1-z))
    mean_cost = np.mean(costs)
    print(f"mean_cost = {mean_cost}")
    print("="*30) 

H = [-0.13416408 -0.04472136  0.04472136  0.13416408]
z = [0.4665092  0.48882152 0.51117848 0.5334908 ]
grad_a = -0.42224770144375845
grad_b = 2.7755575615628914e-17
update a = 0.14222477014437584, update b = -2.7755575615628915e-18
mean_cost = 0.6496749678557904
H = [-0.19081455 -0.06360485  0.06360485  0.19081455]
z = [0.45244058 0.48410415 0.51589585 0.54755942]
grad_a = -0.41175534454951257
grad_b = -2.7755575615628914e-17
update a = 0.1834003045993271, update b = 0.0
mean_cost = 0.6320673287872615
H = [-0.24605733 -0.08201911  0.08201911  0.24605733]
z = [0.43879416 0.47950671 0.52049329 0.56120584]
grad_a = -0.4015730318619577
grad_b = 0.0
update a = 0.22355760778552286, update b = 0.0
mean_cost = 0.6153229046100694
H = [-0.299934 -0.099978  0.099978  0.299934]
z = [0.42557362 0.4750263  0.5249737  0.57442638]
grad_a = -0.39170257011507503
grad_b = 0.0
update a = 0.26272786479703036, update b = 0.0
mean_cost = 0.5993952198102015
H = [-0.35248642 -0.11749547  0.11749547  0.3524864