In [1]:
import numpy as np
import torch 
from math import e

In [2]:
X = np.array([160, 170, 180, 190])

X

array([160, 170, 180, 190])

In [3]:
y = np.array([0, 0, 1, 1])

y

array([0, 0, 1, 1])

In [7]:
X_mean = np.mean(X)

X_mean

np.float64(175.0)

In [9]:
X_std = np.std(X)
X_std

np.float64(11.180339887498949)

In [11]:
X_norm = (X - X_mean) / X_std

X_norm

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [12]:
X_norm_tensor = torch.tensor(X_norm, dtype = torch.float32)

X_norm_tensor

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [14]:
y_tensor = torch.tensor(y, dtype = torch.float32)

y_tensor

tensor([0., 0., 1., 1.])

In [15]:
a = torch.tensor(0.1, dtype = torch.float32, requires_grad = True)
b = torch.tensor(0, dtype = torch.float32, requires_grad = True)

In [17]:
print(a)
print(b)


tensor(0.1000, requires_grad=True)
tensor(0., requires_grad=True)


In [18]:
learning_rate = 0.1 
epochs = 1000

In [21]:
optimizer = torch.optim.SGD([a,b], lr = learning_rate) #옵티마이저 객체 선언

optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [22]:
epsilon = 1e-7

In [33]:
for epoch in range(epochs):
    optimizer.zero_grad()
    
    H = a * X_norm_tensor + b 
    z = torch.sigmoid(H)
    
    z_safe = torch.clamp(z, epsilon, 1-epsilon)
    
    costs = -(y_tensor * torch.log(z_safe) + (1 - y_tensor) * torch.log(1-z_safe))
    mean_cost = torch.mean(costs) 
    mean_cost.backward()
    
    optimizer.step()
    
    if epoch % 100 == 0 or epoch == epochs -1 :
        print(
            f"epoch = {epoch}",
            f"Cost = {mean_cost}",
            f"a = {a.item()}",
            f"b = {b.item()}"
        )
        
    if epoch < 3: 
        grad_a = a.grad.item()
        grad_b = b.grad.item()
        
        print( f"(확인용) a.grad= {grad_a}, b.grad= {grad_b}")

epoch = 0 Cost = 0.012325435876846313 a = 8.254383087158203 b = 1.1343763617333025e-07
(확인용) a.grad= -0.005451736971735954, b.grad= 1.4901161193847656e-08
(확인용) a.grad= -0.005450439173728228, b.grad= 9.313225746154785e-09
(확인용) a.grad= -0.005449141841381788, b.grad= 4.6566128730773926e-09
epoch = 100 Cost = 0.012035136111080647 a = 8.308253288269043 b = 1.153002813225612e-07
epoch = 200 Cost = 0.011758076027035713 a = 8.360880851745605 b = 1.0994516230766749e-07
epoch = 300 Cost = 0.011493336409330368 a = 8.412320137023926 b = 1.125528967804712e-07
epoch = 400 Cost = 0.01124018058180809 a = 8.462625503540039 b = 1.131582791913388e-07
epoch = 500 Cost = 0.010997874662280083 a = 8.51184368133545 b = 9.951438784128186e-08
epoch = 600 Cost = 0.010765641927719116 a = 8.560022354125977 b = 1.1087655593655654e-07
epoch = 700 Cost = 0.010542966425418854 a = 8.607203483581543 b = 1.0025947005942726e-07
epoch = 800 Cost = 0.010329258628189564 a = 8.653424263000488 b = 1.1278574874040714e-07
epoc