In [1]:
import numpy as np

import tensorflow as tf

import pandas as pd

In [2]:
np.random.seed(42)
tf.random.set_seed(42)

In [3]:
H_example = np.array([[-3.0],[-1.0], [0.0], [1.0], [3.0]])
H_example

array([[-3.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 3.]])

In [4]:
tf.sigmoid(H_example)


<tf.Tensor: shape=(5, 1), dtype=float64, numpy=
array([[0.04742587],
       [0.26894142],
       [0.5       ],
       [0.73105858],
       [0.95257413]])>

In [5]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape = 1, ), # 입력: x_norm 칸수 (1칸)
    tf.keras.layers.Dense(1)
])

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [7]:
X = np.array([160, 170, 180, 190], dtype = np.float32).reshape(-1, 1)
print("입력값 X =", X)

입력값 X = [[160.]
 [170.]
 [180.]
 [190.]]


In [8]:
y = np.array([0, 0, 1, 1], dtype = np.float32).reshape(-1, 1)
print("정답값 y =", y)

정답값 y = [[0.]
 [0.]
 [1.]
 [1.]]


In [9]:
X_mean = X.mean()

In [10]:
X_std = X.std()

In [11]:
X_norm = (X - X_mean) / X_std 

In [12]:
H_before = model(X_norm) #선형회귀 값
H_before

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.17605057],
       [-0.05868352],
       [ 0.05868352],
       [ 0.17605057]], dtype=float32)>

In [13]:
z_before = tf.sigmoid(H_before)

z_before

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.4561007 ],
       [0.48533332],
       [0.5146667 ],
       [0.5438993 ]], dtype=float32)>

In [14]:
H_before.numpy() # 파이토치에선 값만 보려면 .item()을 썼으나, tensorflow 에선 .numpy()로 볼 수 있음. 추가로 넘파이 뒤에 [:]를 사용하면 필터링 가능

array([[-0.17605057],
       [-0.05868352],
       [ 0.05868352],
       [ 0.17605057]], dtype=float32)

In [15]:
lr = 0.1
ep = 1000

model.compile(  # H 는 선형회귀 값이지 확률이 아니다!
     optimizer = tf.keras.optimizers.SGD(learning_rate = lr)   # 한번에 기입!
    ,loss = tf.keras.losses.BinaryCrossentropy(from_logits= True)
) 


In [18]:
history = model.fit( # 해당 반복 원할 시 .history 할 것.
    X_norm,
    y,
    epochs = ep,
    verbose = 1
)

Epoch 1/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0237
Epoch 2/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0237
Epoch 3/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.0236
Epoch 4/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0236
Epoch 5/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.0236
Epoch 6/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0236
Epoch 7/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0236
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.0236
Epoch 9/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0236
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.0236
Epoch 11/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0236
Epoch 12/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0235
Epoch 13/1000
1/1 [============================

In [19]:
list(enumerate(history.history["loss"])) #enumerate 는 인덱스 , 전부 보려면 앞에 list 씌우면 됨.

[(0, 0.023662663996219635),
 (1, 0.023651879280805588),
 (2, 0.023641105741262436),
 (3, 0.023630335927009583),
 (4, 0.023619582876563072),
 (5, 0.023608839139342308),
 (6, 0.023598093539476395),
 (7, 0.023587364703416824),
 (8, 0.023576639592647552),
 (9, 0.023565929383039474),
 (10, 0.023555224761366844),
 (11, 0.02354453317821026),
 (12, 0.02353385090827942),
 (13, 0.023523177951574326),
 (14, 0.02351251058280468),
 (15, 0.023501859977841377),
 (16, 0.023491211235523224),
 (17, 0.023480579257011414),
 (18, 0.02346995659172535),
 (19, 0.023459339514374733),
 (20, 0.023448733612895012),
 (21, 0.023438135161995888),
 (22, 0.023427551612257957),
 (23, 0.023416977375745773),
 (24, 0.02340640500187874),
 (25, 0.023395849391818047),
 (26, 0.02338530123233795),
 (27, 0.023374764248728752),
 (28, 0.0233642365783453),
 (29, 0.023353716358542442),
 (30, 0.023343205451965332),
 (31, 0.023332709446549416),
 (32, 0.02332221157848835),
 (33, 0.023311732336878777),
 (34, 0.0233012605458498),
 (35, 

In [24]:
for epoch_index, mean_cost in enumerate(history.history["loss"]):
    if epoch_index % 100 == 0 or epoch_index == ep -1:
        print(f"epoch = {epoch_index}, mean_cost = {mean_cost}") # 에폭 인덱스에 대입 / mean_cost는 history loss 값

epoch = 0, mean_cost = 0.023662663996219635
epoch = 100, mean_cost = 0.022629933431744576
epoch = 200, mean_cost = 0.021682554855942726
epoch = 300, mean_cost = 0.02081041783094406
epoch = 400, mean_cost = 0.02000495418906212
epoch = 500, mean_cost = 0.01925879716873169
epoch = 600, mean_cost = 0.01856570690870285
epoch = 700, mean_cost = 0.017920227721333504
epoch = 800, mean_cost = 0.01731763780117035
epoch = 900, mean_cost = 0.01675380952656269
epoch = 999, mean_cost = 0.016230273991823196


In [28]:
weight, bias = model.layers[-1].get_weights()

In [31]:
weight[0][0] #2차원 배열 → [0] 첫번째는 배열 순서 /[0]  두번째는 값 

7.6314697

In [33]:
bias

array([1.4999478e-09], dtype=float32)

In [36]:
H = model(X_norm)

In [37]:
H

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-10.238691 ],
       [ -3.4128969],
       [  3.4128969],
       [ 10.238691 ]], dtype=float32)>

In [41]:
tf.sigmoid(H) 


<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[3.5758341e-05],
       [3.1894829e-02],
       [9.6810514e-01],
       [9.9996424e-01]], dtype=float32)>

In [44]:
input_value = 185

input_norm = (input_value - X_mean) / X_std

input_norm # 2차원 배열로 바꿔야함.

0.8944271969412381

In [48]:
input_norm_array = np.array([[input_norm]], dtype = np.float32) #2차원 배열로 바꿈 → 텐서플로우는 64비트 실수는 계산이 안됨 → 32비트로 바꿔야함.
input_norm_array

array([[0.8944272]], dtype=float32)

In [50]:
H_new = model(input_norm_array) #아직 확률로 바꾸지 않음

In [54]:
probability = tf.sigmoid(H_new)

probability

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.9989158]], dtype=float32)>

In [58]:
"농구선수 인가봐!" if probability.numpy().item() >= 0.5 else "아닌가봐!" #값만 보려면 .item()

'농구선수 인가봐!'