In [17]:
# !pip install pandas

In [18]:
import pandas as pd

df = pd.DataFrame({
    "temperature": [10, 7, 4, 0],
    "sales": [30, 50, 60, 80]
})
display(df)

,temperature,sales
0,10,30
1,7,50
2,4,60
3,0,80


In [19]:
X = df[["temperature"]].values.astype("float32")   #줄 번호 없앤다! : .values / 입력과 찐의 값이 정수여야 함: .astype("float32")

X           # 2 차원배열로 하고싶다! : [ ] 괄호 하나 더 씌우기

array([[10.],
       [ 7.],
       [ 4.],
       [ 0.]], dtype=float32)

In [20]:
y = df[["sales"]].values.astype("float32")   #줄 번호 없앤다! : .values / 입력과 찐의 값이 정수여야 함: .astype("float32")

y           # 2 차원배열로 하고싶다! : [ ] 괄호 하나 더 씌우기

array([[30.],
       [50.],
       [60.],
       [80.]], dtype=float32)

In [21]:
# X 값은 입력 / y 는 찐 값
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

In [22]:
X

array([[10.],
       [ 7.],
       [ 4.],
       [ 0.]], dtype=float32)

In [23]:
y

array([[30.],
       [50.],
       [60.],
       [80.]], dtype=float32)

In [24]:
model = keras.Sequential([
    layers.Dense(1, input_shape=(1,)) #교안 상에는 빠져있는 내용
])  #└ 선형회귀   /    └입력값 x 의 칸, 줄 수  → 줄은 생략 가능 → x → 1칸 4줄

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(
    optimizer = keras.optimizers.SGD(learning_rate= 0.01),
    loss = "mse"
    )

In [27]:
history = model.fit(X, y, epochs = 10000, verbose = 0) # 입력값 / 찐   어떻게 학습이 되는지 확인 : history 에 닮기

In [28]:
history.history["loss"][-1]  #cost 가 어떻게 변하는지 확인  

4.337896823883057

In [29]:
weight, bias = model.layers[0].get_weights()

a_value = weight[0][0]
b_value = bias[0]
print(f"weight={weight[0][0]}")
print(f"bias={bias[0]}")

weight=-4.8401103019714355
bias=80.41039276123047


In [30]:
X

array([[10.],
       [ 7.],
       [ 4.],
       [ 0.]], dtype=float32)

In [31]:
X * a_value + b_value

array([[32.00929],
       [46.52962],
       [61.04995],
       [80.41039]], dtype=float32)

In [33]:
model.predict(X)

1/1 [==============================] - 0s 21ms/step


array([[32.00929],
       [46.52962],
       [61.04995],
       [80.41039]], dtype=float32)

In [35]:
np.array([[5]] , dtype ="float32") * a_value + b_value

array([[56.20984]], dtype=float32)

In [36]:
model.predict(np.array([[5]] , dtype ="float32") * a_value + b_value)

1/1 [==============================] - 0s 14ms/step


array([[-191.65143]], dtype=float32)