In [20]:
from math import e 

In [ ]:
1/(1 + e **-(-5) )$

0.006692850924284857

In [22]:
1/(1+e**-(0)) # 선형 회귀 H(x) 값이 0일 경우 시그모이드 값: 0.5

0.5

In [23]:
from math import log 

In [24]:
log(2.71828) # log e의 e → 1 (1번 곱한 것)

0.999999327347282

# 시그모이드 예제 추가

In [25]:
import numpy as np
from math import e

X = np.array([160, 170, 180, 190])

X

array([160, 170, 180, 190])

In [26]:
y = np.array([0, 0 ,1 ,1])

y

array([0, 0, 1, 1])

In [27]:
a = 0.1
b = -17

In [28]:
H = a * X + b

In [30]:
def sigmoid(H):
    return 1 / (1 + e**(-H))


In [31]:
z = sigmoid(H)

print("시그모이드 예측 확률 z:", z)

시그모이드 예측 확률 z: [0.26894142 0.5        0.73105858 0.88079708]


In [32]:
costs = -(y * np.log(z) + (1-y)*np.log(1-z))

costs

array([0.31326169, 0.69314718, 0.31326169, 0.12692801])

In [33]:
np.mean(costs)

np.float64(0.36164964165984087)